### ISSUE TITLE
pressing backspace exits menu

### ISSUE THREAD

**Issue by Slavmen** [esx-framework/esx_menu_default#36]
when i press backspace, menu closes instead of going 1 step back

**Comment by NessAPI** [comment]
Is this on all your scripts using this dependency?

**Comment by Slavmen** [comment]
Yes, on all esx scripts that use the menu. I don't know if it makes difference that it's list menu.

**Comment by NessAPI** [comment]
> Yes, on all esx scripts that use the menu. I don't know if it makes difference that it's list menu. EDIT: console shows no error


No error in client aswell as server console?

If there are no errors, try another version :)
